import { navigateWorkspace } from './navigation'
import { test, expect } from '@playwright/test'

async function register(page) {
  await page.goto('/register')
  await page.getByLabel(/^Name/).fill('Browsing User')
  await page.getByLabel(/^Email/).fill(`browsing-${Date.now()}@example.com`)
  await page.getByLabel(/^Password/).fill('a-long-browser-test-password')
  await page.getByLabel(/^Confirm password/).fill('a-long-browser-test-password')
  await page.getByRole('button', { name: 'Create account' }).click()
  await page.getByLabel(/^Currency/).selectOption('EUR')
  await page.getByLabel(/^Timezone/).selectOption('UTC')
  await page.getByRole('button', { name: 'Save preferences' }).click()
  await expect(page.getByText('Preferences saved.')).toBeVisible()
}

// Seed through the authenticated API with the browser's CSRF cookie.
async function create(page, path, values) {
  return page.evaluate(async ({ path, values }) => {
    const csrf = document.cookie.split('; ').find(cookie => cookie.startsWith('XSRF-TOKEN='))?.split('=')[1]
    const response = await fetch(`/api/${path}`, { method: 'POST', headers: { 'Content-Type': 'application/json', Accept: 'application/json', 'X-XSRF-TOKEN': decodeURIComponent(csrf) }, body: JSON.stringify(values) })
    if (!response.ok) throw new Error(`Seed failed: ${response.status}`)
    return (await response.json()).data
  }, { path, values })
}

test('browses server pages, combines filters, recovers from validation and deletes the final page row', async ({ page }) => {
  await register(page)
  const account = await create(page, 'accounts', { name: 'Bank', type: 'checking', opening_balance: '100', opening_date: '2026-01-01' })
  const category = await create(page, 'categories', { name: 'Browser food', type: 'expense' })
  for (let i = 1; i <= 11; i++) {
    await create(page, 'transactions', { account_id: account.id, category_id: category.id, type: 'expense', amount: `${i}.00`, date: '2026-02-01', description: `Purchase ${i}`, notes: i === 3 ? 'Special receipt' : '' })
  }
  await navigateWorkspace(page, 'Activity')
  await page.getByLabel('Results per page').selectOption('10')
  await page.getByLabel('Sort by').selectOption('amount')
  await page.getByLabel('Sort direction').selectOption('asc')
  await page.getByRole('button', { name: 'Apply filters' }).click()
  await expect(page.getByText('11 results · Page 1 of 2')).toBeVisible()
  await expect(page.getByRole('article')).toHaveCount(10)
  await expect(page.getByRole('article').first()).toHaveAccessibleName('Purchase 1')
  await page.getByRole('button', { name: 'Next page' }).click()
  await expect(page.getByRole('article')).toHaveCount(1)
  await expect(page.getByRole('article').first()).toHaveAccessibleName('Purchase 11')
  await page.getByRole('article').getByRole('button').click()
  await page.getByRole('dialog', { name: 'Edit transaction' }).getByRole('button', { name: 'Delete', exact: true }).click()
  await page.getByRole('button', { name: 'Delete transaction', exact: true }).click()
  await expect(page.getByText('10 results · Page 1 of 1')).toBeVisible()
  await page.getByLabel('Search description or notes').fill('special')
  await page.getByLabel('Filter account').selectOption(String(account.id))
  await page.getByLabel('Filter category').selectOption(String(category.id))
  await page.getByLabel('Filter type').selectOption('expense')
  await page.getByLabel('From date').fill('2026-02-01')
  await page.getByLabel('To date').fill('2026-02-01')
  await page.getByLabel('Minimum amount').fill('3.00')
  await page.getByLabel('Maximum amount').fill('3.00')
  await page.getByRole('button', { name: 'Apply filters' }).click()
  await expect(page.getByRole('article')).toHaveCount(1)
  await expect(page.getByRole('article')).toHaveAccessibleName('Purchase 3')
  await page.getByRole('article').getByRole('button').click()
  await page.getByLabel(/^Notes/).fill('Special corrected receipt')
  await page.getByRole('button', { name: 'Save transaction' }).click()
  await expect(page.getByRole('article')).toContainText('Special corrected receipt')
  await expect(page.getByLabel('Search description or notes')).toHaveValue('special')
  await page.getByLabel('Maximum amount').fill('2.00')
  await page.getByRole('button', { name: 'Apply filters' }).click()
  await expect(page.getByText('Maximum amount must be at least the minimum.')).toBeVisible()
  await page.getByRole('button', { name: 'Reset filters' }).click()
  await expect(page.getByRole('article')).toHaveCount(10)
  await page.getByLabel('Search description or notes').fill('not found')
  await page.getByRole('button', { name: 'Apply filters' }).click()
  await expect(page.getByText('No activity matches these filters.')).toBeVisible()
  await page.getByRole('button', { name: 'Reset filters' }).click()
  await expect(page.getByRole('article')).toHaveCount(10)
})

test('transfers money, shows direction in both histories, and corrects and deletes one logical transfer', async ({ page }) => {
  const errors = []
  page.on('pageerror', error => errors.push(error.message))
  await page.setViewportSize({ width: 390, height: 844 })
  await register(page)
  const bank = await create(page, 'accounts', { name: 'Bank', type: 'checking', opening_balance: '100', opening_date: '2026-01-01' })
  const cash = await create(page, 'accounts', { name: 'Cash', type: 'cash', opening_balance: '0', opening_date: '2026-01-01' })
  await navigateWorkspace(page, 'Activity')
  await page.getByRole('main').getByRole('button', { name: 'Add transaction' }).click()
  await page.getByRole('dialog', { name: 'Add transaction' }).getByRole('button', { name: 'Transfer', exact: true }).click()
  await page.getByLabel(/^From account/).selectOption(String(bank.id))
  await page.getByLabel(/^To account/).selectOption(String(bank.id))
  await page.getByLabel(/^Amount/).fill('10.25')
  await page.getByLabel(/^Description/, { exact: false }).fill('ATM withdrawal')
  await page.getByRole('button', { name: 'Save transfer' }).click()
  await expect(page.getByText('Choose a different destination account.')).toBeVisible()
  await page.getByLabel(/^To account/).selectOption(String(cash.id))
  await page.getByRole('button', { name: 'Save transfer' }).click()
  await expect(page.getByRole('article', { name: 'ATM withdrawal' })).toContainText('Bank → Cash')
  await expect(page.getByText('1 results · Page 1 of 1')).toBeVisible()
  await navigateWorkspace(page, 'Accounts')
  await expect(page.getByRole('article', { name: 'Bank', exact: true })).toContainText('Current balance: €89.75')
  await expect(page.getByRole('article', { name: 'Cash', exact: true })).toContainText('Current balance: €10.25')
  await page.getByRole('article', { name: 'Cash', exact: true }).getByRole('link', { name: 'View history' }).click()
  await expect(page.getByRole('article', { name: 'ATM withdrawal' })).toContainText('Transfer in: +€10.25')
  await page.getByRole('link', { name: 'Back to accounts' }).click()
  await page.getByRole('article', { name: 'Bank', exact: true }).getByRole('button', { name: 'Archive', exact: true }).click()
  await expect(page.getByRole('article', { name: 'Bank', exact: true })).toContainText('Archived')
  await page.getByRole('article', { name: 'Bank', exact: true }).getByRole('link', { name: 'View history' }).click()
  await expect(page.getByRole('article', { name: 'ATM withdrawal' })).toContainText('Transfer out: -€10.25')
  await page.getByRole('article', { name: 'ATM withdrawal' }).getByRole('button').click()
  await expect(page.getByRole('dialog', { name: 'Edit transfer' })).toBeVisible()
  await page.getByLabel(/^Amount/).fill('20.01')
  await page.getByRole('button', { name: 'Save transfer' }).click()
  await expect(page.getByText(/Current balance: €79.99/)).toBeVisible()
  await page.reload()
  await expect(page.getByRole('article', { name: 'ATM withdrawal' })).toContainText('Transfer out: -€20.01')
  await page.getByRole('article', { name: 'ATM withdrawal' }).getByRole('button').click()
  await page.getByRole('dialog', { name: 'Edit transfer' }).getByRole('button', { name: 'Delete', exact: true }).click()
  await page.getByRole('button', { name: 'Delete transfer', exact: true }).click()
  await expect(page.getByText(/Current balance: €100.00/)).toBeVisible()
  await expect(page.getByText('No activity matches these filters.')).toBeVisible()
  await page.getByRole('link', { name: 'Back to accounts' }).click()
  await expect(page.getByRole('article', { name: 'Cash', exact: true })).toContainText('Current balance: €0.00')
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBeTruthy()
  expect(errors).toEqual([])
})
