import { navigateWorkspace } from './navigation'
import { test, expect } from '@playwright/test'

test('manages budgets and recurring rules with validation and mobile navigation', async ({ page }) => {
  const errors = []
  page.on('pageerror', error => errors.push(error.message))
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto('/register')
  await page.getByLabel(/^Name/).fill('Extended User')
  await page.getByLabel(/^Email/).fill(`extended-${Date.now()}@example.com`)
  await page.getByLabel(/^Password/).fill('a-long-browser-test-password')
  await page.getByLabel(/^Confirm password/).fill('a-long-browser-test-password')
  await page.getByRole('button', { name: 'Create account' }).click()
  await page.getByLabel(/^Currency/).selectOption('EUR')
  await page.getByLabel(/^Timezone/).selectOption('UTC')
  await page.getByRole('button', { name: 'Save preferences' }).click()
  await expect(page.getByText('Preferences saved.')).toBeVisible()
  const ids = await page.evaluate(async () => {
    const csrf = decodeURIComponent(document.cookie.split('; ').find(c => c.startsWith('XSRF-TOKEN=')).split('=')[1])
    async function write(path, values) {
      const response = await fetch(`/api/${path}`, { method: 'POST', headers: { Accept: 'application/json', 'Content-Type': 'application/json', 'X-XSRF-TOKEN': csrf }, body: JSON.stringify(values) })
      if (!response.ok) throw new Error(`Seed ${path} failed: ${response.status} ${await response.text()}`)
      return (await response.json()).data
    }
    const account = await write('accounts', { name: 'Bank', type: 'checking', opening_balance: '100.00', opening_date: '2026-01-01' })
    const category = await write('categories', { name: 'Extended subscriptions', type: 'expense' })
    await write('transactions', { account_id: account.id, category_id: category.id, type: 'expense', amount: '12.01', date: '2026-02-28', description: 'Subscription payment' })
    return { account: String(account.id), category: String(category.id) }
  })
  await navigateWorkspace(page, 'Budgets')
  await page.getByLabel('Budget month').fill('2026-02')
  await page.getByRole('button', { name: 'Add budget' }).click()
  await page.getByLabel(/^Expense category/).selectOption(ids.category)
  await page.getByLabel(/^Monthly limit/).fill('10.00')
  await page.getByRole('button', { name: 'Save budget' }).click()
  const budget = page.getByRole('article', { name: 'Extended subscriptions', exact: true })
  await expect(budget).toContainText('Remaining: -€2.01')
  await expect(budget).toContainText('120.1% used')
  await page.getByRole('button', { name: 'Add budget' }).click()
  await page.getByLabel(/^Expense category/).selectOption(ids.category)
  await page.getByLabel(/^Monthly limit/).fill('20.00')
  await page.getByRole('button', { name: 'Save budget' }).click()
  await expect(page.getByText('This category already has a budget for this month.')).toBeVisible()
  await page.getByRole('button', { name: 'Cancel', exact: true }).click()
  await budget.getByRole('button', { name: 'Edit', exact: true }).click()
  await page.getByLabel(/^Monthly limit/).fill('20.00')
  await page.getByRole('button', { name: 'Save budget' }).click()
  await expect(budget).toContainText('Remaining: €7.99')
  await navigateWorkspace(page, 'Overview')
  await page.getByLabel('Summary month').fill('2026-02')
  await expect(page.getByRole('region', { name: 'Monthly budgets', exact: true })).toContainText('Spent: €12.01')
  await navigateWorkspace(page, 'Activity', 'Scheduled')
  await page.getByRole('button', { name: 'Add rule' }).click()
  await page.getByLabel(/^Account/).selectOption(ids.account)
  await page.getByLabel(/^Category/).selectOption(ids.category)
  await page.getByLabel(/^Amount/).fill('8.50')
  await page.getByLabel(/^Description/).fill('Music subscription')
  await page.getByLabel(/^Start date/).fill('2027-01-31')
  await page.getByRole('button', { name: 'Save rule' }).click()
  const rule = page.getByRole('article', { name: 'Music subscription', exact: true })
  await expect(rule).toContainText('Next due: Jan 31, 2027')
  await rule.getByRole('button', { name: 'Pause', exact: true }).click()
  await expect(rule).toContainText('Paused')
  await rule.getByRole('button', { name: 'Resume', exact: true }).click()
  await expect(rule).toContainText('Next due: Jan 31, 2027')
  await rule.getByRole('button', { name: 'Edit', exact: true }).click()
  await page.getByLabel(/^Amount/).fill('9.50')
  await page.getByRole('button', { name: 'Save rule' }).click()
  await expect(rule).toContainText('€9.50')
  await page.reload()
  await expect(rule).toContainText('€9.50')
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBeTruthy()
  await rule.getByRole('button', { name: 'Delete', exact: true }).click()
  await page.getByRole('button', { name: 'Delete rule', exact: true }).click()
  await expect(rule).toHaveCount(0)
  await navigateWorkspace(page, 'Budgets')
  await page.getByLabel('Budget month').fill('2026-02')
  await budget.getByRole('button', { name: 'Delete', exact: true }).click()
  await page.getByRole('button', { name: 'Delete budget', exact: true }).click()
  await expect(budget).toHaveCount(0)
  expect(errors).toEqual([])
})
