import { navigateWorkspace } from './navigation'
import { test, expect } from '@playwright/test'

test('shows exact dashboard totals, month selection, archived balances and refreshed corrections on mobile', async ({ page }) => {
  const errors = []
  page.on('pageerror', error => errors.push(error.message))
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto('/register')
  await page.getByLabel(/^Name/).fill('Dashboard User')
  await page.getByLabel(/^Email/).fill(`dashboard-${Date.now()}@example.com`)
  await page.getByLabel(/^Password/).fill('a-long-browser-test-password')
  await page.getByLabel(/^Confirm password/).fill('a-long-browser-test-password')
  await page.getByRole('button', { name: 'Create account' }).click()
  await page.getByLabel(/^Currency/).selectOption('EUR')
  await page.getByLabel(/^Timezone/).selectOption('UTC')
  await page.getByRole('button', { name: 'Save preferences' }).click()
  await expect(page.getByText('Preferences saved.')).toBeVisible()
  await navigateWorkspace(page, 'Overview')
  await expect(page.getByText(/No accounts yet/)).toBeVisible()
  await expect(page.getByRole('region', { name: 'Total balance', exact: true })).toContainText('EUR 0.00')

  // Seed authenticated records, then exercise the rendered summaries and correction flow.
  await page.evaluate(async () => {
    const csrf = decodeURIComponent(document.cookie.split('; ').find(c => c.startsWith('XSRF-TOKEN=')).split('=')[1])
    async function write(path, values, method = 'POST') {
      const response = await fetch(`/api/${path}`, { method, headers: { Accept: 'application/json', 'Content-Type': 'application/json', 'X-XSRF-TOKEN': csrf }, body: JSON.stringify(values) })
      if (!response.ok) throw new Error(`Seed failed: ${response.status}`)
      return (await response.json()).data
    }
    const bank = await write('accounts', { name: 'Bank', type: 'checking', opening_balance: '100.00', opening_date: '2026-01-01' })
    const cash = await write('accounts', { name: 'Cash', type: 'cash', opening_balance: '-20.00', opening_date: '2026-01-01' })
    const pay = await write('categories', { name: 'Dashboard pay', type: 'income' })
    const food = await write('categories', { name: 'Dashboard food', type: 'expense' })
    await write('transactions', { account_id: bank.id, category_id: pay.id, type: 'income', amount: '100.01', date: '2026-02-01', description: 'Monthly pay' })
    await write('transactions', { account_id: cash.id, category_id: food.id, type: 'expense', amount: '20.02', date: '2026-02-28', description: 'Dinner' })
    await write('transfers', { source_account_id: bank.id, destination_account_id: cash.id, amount: '12.34', date: '2026-02-15', description: 'Cash withdrawal' })
    await write(`accounts/${cash.id}`, { is_active: false }, 'PATCH')
  })
  await page.getByLabel('Summary month').fill('2026-02')
  await expect(page.getByRole('region', { name: 'Total balance', exact: true })).toContainText('EUR 159.99')
  await expect(page.getByRole('region', { name: 'Monthly income', exact: true })).toContainText('EUR 100.01')
  await expect(page.getByRole('region', { name: 'Monthly expenses', exact: true })).toContainText('EUR 20.02')
  await expect(page.getByRole('region', { name: 'Net cash flow', exact: true })).toContainText('EUR 79.99')
  await expect(page.getByRole('article', { name: 'Cash', exact: true })).toContainText('Archived')
  await expect(page.getByRole('article', { name: 'Cash', exact: true })).toContainText('EUR -27.68')
  await expect(page.getByRole('region', { name: 'Recent activity', exact: true }).getByRole('article')).toHaveCount(3)
  await expect(page.getByRole('article', { name: 'Cash withdrawal', exact: true })).toContainText('Bank → Cash')
  await page.getByLabel('Summary month').fill('2026-01')
  await expect(page.getByRole('region', { name: 'Monthly income', exact: true })).toContainText('EUR 0.00')
  await expect(page.getByRole('region', { name: 'Total balance', exact: true })).toContainText('EUR 159.99')
  await page.getByRole('article', { name: 'Cash', exact: true }).getByRole('link', { name: 'View history' }).click()
  await page.getByRole('article', { name: 'Dinner', exact: true }).getByRole('button', { name: 'Edit', exact: true }).click()
  await page.getByLabel(/^Amount/).fill('30.02')
  await page.getByRole('button', { name: 'Save entry' }).click()
  await expect(page.getByRole('article', { name: 'Dinner', exact: true })).toContainText('EUR 30.02')
  await navigateWorkspace(page, 'Overview')
  await page.getByLabel('Summary month').fill('2026-02')
  await expect(page.getByRole('region', { name: 'Net cash flow', exact: true })).toContainText('EUR 69.99')
  await expect(page.getByRole('region', { name: 'Total balance', exact: true })).toContainText('EUR 149.99')
  await page.getByRole('button', { name: 'Refresh', exact: true }).click()
  await expect(page.getByRole('region', { name: 'Total balance', exact: true })).toContainText('EUR 149.99')
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBeTruthy()
  await page.screenshot({ path: test.info().outputPath('dashboard-mobile.png'), fullPage: true })
  expect(errors).toEqual([])
})
