import { test, expect } from '@playwright/test'

test('sets preferences, manages accounts, and customizes categories on a small screen', async ({ page }) => {
  const errors = []
  page.on('pageerror', error => errors.push(error.message))
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto('/register')
  await page.getByLabel(/^Name/).fill('Finance User')
  await page.getByLabel(/^Email/).fill(`finance-${Date.now()}@example.com`)
  await page.getByLabel(/^Password/).fill('a-long-browser-test-password')
  await page.getByLabel(/^Confirm password/).fill('a-long-browser-test-password')
  await page.getByRole('button', { name: 'Create account' }).click()
  await expect(page).toHaveURL(/\/settings$/)
  await expect(page.getByLabel(/^Currency/)).toHaveValue('')
  await page.getByLabel(/^Currency/).selectOption('RSD')
  await page.getByLabel(/^Timezone/).selectOption('Europe/Belgrade')
  await page.getByRole('button', { name: 'Save preferences' }).click()
  await expect(page.getByText('Preferences saved.')).toBeVisible()
  await page.reload()
  await expect(page.getByLabel(/^Currency/)).toHaveValue('RSD')
  await expect(page.getByLabel(/^Timezone/)).toHaveValue('Europe/Belgrade')

  await page.getByRole('link', { name: 'Accounts', exact: true }).click()
  await expect(page.getByText('No accounts yet.', { exact: false })).toBeVisible()
  await page.getByRole('button', { name: 'Add account' }).click()
  await page.getByLabel(/^Account name/).fill('Everyday cash')
  await page.getByLabel(/^Account type/).selectOption('cash')
  await page.getByLabel(/^Opening balance/).fill('1234.567')
  await page.getByRole('button', { name: 'Save account' }).click()
  await expect(page.getByText('Enter an amount with a dot', { exact: false })).toBeVisible()
  await page.getByLabel(/^Opening balance/).fill('1234.56')
  await page.getByRole('button', { name: 'Save account' }).click()
  let account = page.getByRole('article', { name: 'Everyday cash' })
  await expect(account).toContainText('RSD 1234.56')
  await account.getByRole('button', { name: 'Edit', exact: true }).click()
  await page.getByLabel(/^Account name/).fill('Wallet')
  await page.getByLabel(/^Opening balance/).fill('-0.01')
  await page.getByRole('button', { name: 'Save account' }).click()
  account = page.getByRole('article', { name: 'Wallet' })
  await expect(account).toContainText('RSD -0.01')
  await account.getByRole('button', { name: 'Archive', exact: true }).click()
  await expect(account).toContainText('Archived')
  await account.getByRole('button', { name: 'Unarchive' }).click()
  await expect(account).toContainText('Active')
  await page.getByRole('link', { name: 'Settings', exact: true }).click()
  await expect(page.getByLabel(/^Currency/)).toBeDisabled()
  await page.getByLabel(/^Timezone/).selectOption('UTC')
  await page.getByRole('button', { name: 'Save preferences' }).click()
  await expect(page.getByText('Preferences saved.')).toBeVisible()

  await page.getByRole('link', { name: 'Categories', exact: true }).click()
  await expect(page.getByRole('article', { name: 'Salary', exact: true })).toBeVisible()
  await expect(page.getByRole('article')).toHaveCount(11)
  await page.getByRole('button', { name: 'Add category' }).click()
  await page.getByLabel(/^Category name/).fill('Coffee')
  await page.getByRole('button', { name: 'Save category' }).click()
  let category = page.getByRole('article', { name: 'Coffee', exact: true })
  await expect(category).toContainText('Expense')
  await category.getByRole('button', { name: 'Edit', exact: true }).click()
  await page.getByLabel(/^Category name/).fill('GROCERIES')
  await page.getByRole('button', { name: 'Save category' }).click()
  await expect(page.getByText('A category with this name and type already exists.')).toBeVisible()
  await page.getByLabel(/^Category name/).fill('Cafe')
  await page.getByLabel(/^Category type/).selectOption('income')
  await page.getByRole('button', { name: 'Save category' }).click()
  category = page.getByRole('article', { name: 'Cafe', exact: true })
  await expect(category).toContainText('Income')
  await category.getByRole('button', { name: 'Delete', exact: true }).click()
  await page.getByRole('button', { name: 'Cancel', exact: true }).click()
  await expect(category).toBeVisible()
  await category.getByRole('button', { name: 'Delete', exact: true }).click()
  await page.getByRole('button', { name: 'Delete category', exact: true }).click()
  await expect(category).toHaveCount(0)

  await page.getByRole('link', { name: 'Accounts', exact: true }).click()
  await page.getByRole('article', { name: 'Wallet' }).getByRole('button', { name: 'Delete', exact: true }).click()
  await page.getByRole('button', { name: 'Delete account', exact: true }).click()
  await expect(page.getByText('No accounts yet.', { exact: false })).toBeVisible()
  await page.getByRole('link', { name: 'Settings', exact: true }).click()
  await expect(page.getByLabel(/^Currency/)).toBeDisabled()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBeTruthy()
  await page.screenshot({ path: test.info().outputPath('settings-mobile.png'), fullPage: true })
  expect(errors).toEqual([])
})
