import { navigateWorkspace } from './navigation'
import { test, expect } from '@playwright/test'

test('manual goals and monthly comparisons work on mobile', async ({ page }) => {
  const errors = []
  page.on('pageerror', error => errors.push(error.message))
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto('/register')
  await page.getByLabel(/^Name/).fill('Goals User')
  await page.getByLabel(/^Email/).fill(`goals-${Date.now()}@example.com`)
  await page.getByLabel(/^Password/).fill('a-long-browser-test-password')
  await page.getByLabel(/^Confirm password/).fill('a-long-browser-test-password')
  await page.getByRole('button', { name: 'Create account' }).click()
  await page.getByLabel(/^Currency/).selectOption('EUR')
  await page.getByLabel(/^Timezone/).selectOption('UTC')
  await page.getByRole('button', { name: 'Save preferences' }).click()
  await expect(page.getByText('Preferences saved.')).toBeVisible()
  await page.evaluate(async () => {
    const csrf = decodeURIComponent(document.cookie.split('; ').find(c => c.startsWith('XSRF-TOKEN=')).split('=')[1])
    async function write(path, values) {
      const response = await fetch(`/api/${path}`, { method: 'POST', headers: { Accept: 'application/json', 'Content-Type': 'application/json', 'X-XSRF-TOKEN': csrf }, body: JSON.stringify(values) })
      if (!response.ok) throw new Error(`Seed failed: ${await response.text()}`)
      return (await response.json()).data
    }
    const account = await write('accounts', { name: 'Bank', type: 'checking', opening_balance: '100.00', opening_date: '2024-01-01' })
    const category = await write('categories', { name: 'Report food', type: 'expense' })
    for (const [date, amount] of [['2024-01-31', '10.00'], ['2024-02-29', '20.02']]) {
      await write('transactions', { account_id: account.id, category_id: category.id, type: 'expense', amount, date, description: 'Food' })
    }
  })
  await navigateWorkspace(page, 'Savings goals')
  await page.getByRole('button', { name: 'Add goal' }).click()
  await page.getByLabel(/^Goal name/).fill('Holiday')
  await page.getByLabel(/^Target amount/).fill('0')
  await page.getByRole('button', { name: 'Save goal' }).click()
  await expect(page.getByText('Target amount must be greater than zero.')).toBeVisible()
  await page.getByLabel(/^Target amount/).fill('100.00')
  await page.getByLabel(/^Saved amount/).fill('25.01')
  await page.getByRole('button', { name: 'Save goal' }).click()
  const goal = page.getByRole('article', { name: 'Holiday', exact: true })
  await expect(goal).toContainText('Remaining: EUR 74.99')
  await goal.getByRole('button', { name: 'Edit' }).click()
  await page.getByLabel(/^Saved amount/).fill('125.00')
  await page.getByRole('button', { name: 'Save goal' }).click()
  await expect(goal).toContainText('125% reached')
  await page.reload()
  await expect(goal).toContainText('125% reached')
  await navigateWorkspace(page, 'Overview')
  await expect(page.getByRole('region', { name: 'Active savings goals' })).toContainText('Holiday')
  await expect(page.getByRole('region', { name: 'Total balance', exact: true })).toContainText('EUR 69.98')
  await navigateWorkspace(page, 'Savings goals')
  for (const status of ['completed', 'cancelled', 'active']) {
    await goal.getByRole('button', { name: 'Edit' }).click()
    await page.getByLabel(/^Status/).selectOption(status)
    await page.getByRole('button', { name: 'Save goal' }).click()
    await expect(goal).toContainText(`Status: ${status}`)
  }
  await goal.getByRole('button', { name: 'Delete', exact: true }).click()
  await page.getByRole('button', { name: 'Delete goal', exact: true }).click()
  await expect(goal).toHaveCount(0)
  await navigateWorkspace(page, 'Reports')
  await page.getByLabel('Report month').fill('2024-02')
  await expect(page.getByRole('region', { name: 'Expenses', exact: true })).toContainText('Change: EUR 10.02')
  await expect(page.getByRole('region', { name: 'Net cash flow', exact: true })).toContainText('Selected: EUR -20.02')
  await expect(page.getByRole('region', { name: 'Spending by category' })).toContainText('Report food')
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBeTruthy()
  await page.getByLabel('Report month').fill('2024-03')
  await expect(page.getByText('No expenses recorded for this month.')).toBeVisible()
  expect(errors).toEqual([])
})
