import { navigateWorkspace } from './navigation'
import { test, expect } from '@playwright/test'

test('records, corrects, and deletes activity with exact balances and protected history', async ({ page }) => {
  const errors = []
  page.on('pageerror', error => errors.push(error.message))
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto('/register')
  await page.getByLabel(/^Name/).fill('Entry User')
  await page.getByLabel(/^Email/).fill(`entries-${Date.now()}@example.com`)
  await page.getByLabel(/^Password/).fill('a-long-browser-test-password')
  await page.getByLabel(/^Confirm password/).fill('a-long-browser-test-password')
  await page.getByRole('button', { name: 'Create account' }).click()
  await page.getByLabel(/^Currency/).selectOption('EUR')
  await page.getByLabel(/^Timezone/).selectOption('UTC')
  await page.getByRole('button', { name: 'Save preferences' }).click()
  await expect(page.getByText('Preferences saved.')).toBeVisible()
  await navigateWorkspace(page, 'Accounts')
  await page.getByRole('button', { name: 'Add account' }).click()
  await page.getByLabel(/^Account name/).fill('Wallet')
  await page.getByLabel(/^Opening balance/).fill('100.00')
  await page.getByLabel(/^Opening date/).fill('2026-01-01')
  await page.getByRole('button', { name: 'Save account' }).click()
  await expect(page.getByRole('article', { name: 'Wallet' })).toBeVisible()
  await navigateWorkspace(page, 'Transactions')
  await page.getByRole('main').getByRole('button', { name: 'Add transaction' }).click()
  const editor = page.getByRole('dialog', { name: 'Add transaction' })
  await expect(page.getByLabel(/^Amount/)).toBeFocused()
  await editor.getByRole('button', { name: 'Income', exact: true }).click()
  await expect(page.getByLabel(/^Account/)).toHaveValue(/\d+/)
  await page.getByLabel(/^Category/).selectOption({ label: 'Salary' })
  await page.getByLabel(/^Amount/).fill('0')
  await page.getByLabel(/^Description/).fill('Pay day')
  await page.getByRole('button', { name: 'Save transaction' }).click()
  await expect(page.getByText('Amount must be greater than zero.', { exact: true })).toBeVisible()
  await page.getByLabel(/^Amount/).fill('0.10')
  await page.getByRole('button', { name: 'Save transaction' }).click()
  await expect(page.getByRole('article', { name: 'Pay day' })).toContainText('Income: +€0.10')
  await expect(page.getByRole('heading', { name: 'Today' })).toBeVisible()
  await page.getByRole('main').getByRole('button', { name: 'Add transaction' }).click()
  await page.getByLabel(/^Category/).selectOption({ label: 'Groceries' })
  await page.getByLabel(/^Amount/).fill('0.20')
  await page.getByLabel(/^Description/).fill('Lunch')
  await page.getByLabel(/^Notes/).fill('A small expense')
  await page.getByRole('button', { name: 'Save transaction' }).click()
  await expect(page.getByRole('article', { name: 'Lunch' })).toContainText('Expense: -€0.20')
  await navigateWorkspace(page, 'Accounts')
  const wallet = page.getByRole('article', { name: 'Wallet' })
  await expect(wallet).toContainText('Current balance: €99.90')
  await wallet.getByRole('button', { name: 'Delete', exact: true }).click()
  await page.getByRole('button', { name: 'Delete account', exact: true }).click()
  await expect(page.getByText('This account has activity.', { exact: false })).toBeVisible()
  await page.getByRole('button', { name: 'Cancel' }).click()
  await wallet.getByRole('button', { name: 'Archive', exact: true }).click()
  await expect(wallet).toContainText('Archived')
  await wallet.getByRole('link', { name: 'View history' }).click()
  await expect(page.getByRole('heading', { name: 'Wallet history' })).toBeVisible()
  await expect(page.getByRole('article')).toHaveCount(2)
  await page.getByRole('article', { name: 'Lunch' }).getByRole('button').click()
  await expect(page.getByRole('dialog', { name: 'Edit transaction' })).toBeVisible()
  await page.getByLabel(/^Amount/).fill('1.20')
  await page.getByRole('button', { name: 'Save transaction' }).click()
  await expect(page.getByText(/Current balance: €98.90/)).toBeVisible()
  await page.reload()
  await expect(page.getByText(/Current balance: €98.90/)).toBeVisible()
  await page.getByRole('article', { name: 'Lunch' }).getByRole('button').click()
  await page.getByRole('dialog', { name: 'Edit transaction' }).getByRole('button', { name: 'Delete', exact: true }).click()
  await page.getByRole('button', { name: 'Delete transaction', exact: true }).click()
  await expect(page.getByText(/Current balance: €100.10/)).toBeVisible()
  await expect(page.getByRole('article')).toHaveCount(1)
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBeTruthy()
  expect(errors).toEqual([])
})
